[package]
name = "bar-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", branch = "master" }
iced = { git = "https://github.com/pop-os/iced.git", branch = "master", features = [
    "tokio",
    "wayland",
    "winit",
    "image"
] }
bar-rs_derive = { path = "crates/bar-rs_derive"}
niri-ipc = "=0.1.10"
serde = { version = "1.0.217", features = ["derive"] }
chrono = "0.4.40"
configparser = "3.1.0"
ctrlc = "3.4.5"
directories = "6.0.0"
notify = "8.0.0"
tokio = { version = "1.44.1", features = ["io-util", "macros", "process", "sync"] }
udev = { version = "0.9.3", features = ["mio"] }
downcast-rs = "2.0.1"
csscolorparser = "0.7.0"
wayfire-rs = "0.2.2"
serde_json = "1.0.140"
reqwest = "0.12.14"
libc = "0.2.171"
regex = "1.11.1"
smithay-client-toolkit = "0.19.2"

[profile.dev.package."*"]
opt-level = 3
