[package]
name = "crabbar"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/pop-os/iced.git", branch = "master", features = [
    "tokio",
    "wayland",
    "winit",
    "image"
] }
bar-rs_derive = { path = "crates/crabbar_derive"}
tokio = { version = "1.44.1", features = ["io-util", "macros", "process", "sync"] }
log = "0.4.27"
env_logger = "0.11.8"

[profile.dev.package."*"]
opt-level = 3
