[package]
name = "crabbar-ipc"
version.workspace = true
edition.workspace = true

[dependencies]
core.workspace = true

clap.workspace = true
serde.workspace = true
anyhow.workspace = true
ron.workspace = true

[lints]
workspace = true
